Fault_Model_ID = 2
Fault_Model_Name = "Faults Interface"
[[Fault_Model]]
ID = 17
Tectonic_Region = "Subduction Interface"
Fault_Name = "Shallow Manila Trench 1"
Rake = 95
Slip_Type = "Thrust,"
Slip_Completeness_Factor = "1,"
Aseismic = 0.99
Aspect_Ratio = 1.5
[[Fault_Model.MFD_Model]]
Model_Name = "YoungsCoppersmithCharacteristic"
MFD_spacing = 0.1
Model_Weight = 0.5
Minimum_Magnitude = 4.8
Maximum_Magnitude = 8
b_value = [ 0.868, 0.057,]

[[Fault_Model.MFD_Model]]
Model_Name = "AndersonLucoArbitrary"
Model_Type = "First"
MFD_spacing = 0.1
Model_Weight = 0.5
Minimum_Magnitude = 4.8
Maximum_Magnitude = 8
b_value = [ 0.868, 0.057,]


[Fault_Model.Fault_Geometry]
Fault_Typology = "Simple"
Fault_Trace = [ 120.056488139794, 20.4888291113274, 120.248077953476, 19.9054132051134, 120.309941095562, 19.5695571601802, 120.219605180908, 19.3186725607661, 120.001607051998, 19.0850858261459, 119.733040431811, 18.7801639580133, 119.636256620232, 18.3047696380102, 119.450875198388, 18.0379783542777, 119.183567567656, 17.5663883580338, 119.078799161775, 17.1497271626316, 119.080829322256, 16.7986816817357, 119.153572081965, 16.4295006746644,]
Upper_Depth = 0
Lower_Depth = 50
Dip = 45
[Fault_Model.Slip]
Value = [ 4.0, 20.0, 25.0, 100.0, 116.0,]
Weight = [ 0.2, 0.25, 0.35, 0.1, 0.1,]
[Fault_Model.Shear_Modulus]
Value = [ 30.0,]
Weight = [ 1.0,]
[Fault_Model.Magnitude_Scaling_Relation]
Value = [ "StrasserInterface",]
Weight = [ 1.0,]
[Fault_Model.Scaling_Relation_Sigma]
Value = [ 0.0,]
Weight = [ 1.0,]
[Fault_Model.Displacement_Length_Ratio]
Value = [ 1.25e-5,]
Weight = [ 1.0,]
[[Fault_Model]]
ID = 18
Tectonic_Region = "Subduction Interface"
Fault_Name = "Shallow Manila Trench 2"
Rake = 95
Slip_Type = "Thrust,"
Slip_Completeness_Factor = "1,"
Aseismic = 0.99
Aspect_Ratio = 1.5
[[Fault_Model.MFD_Model]]
Model_Name = "YoungsCoppersmithCharacteristic"
MFD_spacing = 0.1
Model_Weight = 0.5
Minimum_Magnitude = 4.8
Maximum_Magnitude = 8
b_value = [ 0.868, 0.057,]

[[Fault_Model.MFD_Model]]
Model_Name = "AndersonLucoArbitrary"
Model_Type = "First"
MFD_spacing = 0.1
Model_Weight = 0.5
Minimum_Magnitude = 4.8
Maximum_Magnitude = 8
b_value = [ 0.868, 0.057,]


[Fault_Model.Fault_Geometry]
Fault_Typology = "Simple"
Fault_Trace = [ 119.153572081965, 16.4295006746644, 119.161115880619, 16.1840803955984, 119.048237064563, 15.8212857692178, 119.143208279443, 15.5128191474036, 119.012894916887, 15.2132701218065, 119.054573575693, 14.6418506764076, 119.113289191592, 14.0644876276553,]
Upper_Depth = 0
Lower_Depth = 50
Dip = 45
[Fault_Model.Slip]
Value = [ 4.0, 20.0, 25.0, 100.0, 116.0,]
Weight = [ 0.2, 0.25, 0.35, 0.1, 0.1,]
[Fault_Model.Shear_Modulus]
Value = [ 30.0,]
Weight = [ 1.0,]
[Fault_Model.Magnitude_Scaling_Relation]
Value = [ "StrasserInterface",]
Weight = [ 1.0,]
[Fault_Model.Scaling_Relation_Sigma]
Value = [ 0.0,]
Weight = [ 1.0,]
[Fault_Model.Displacement_Length_Ratio]
Value = [ 1.25e-5,]
Weight = [ 1.0,]
[[Fault_Model]]
ID = 19
Tectonic_Region = "Subduction Interface"
Fault_Name = "Shallow Manila Trench 2"
Rake = 95
Slip_Type = "Thrust,"
Slip_Completeness_Factor = "1,"
Aseismic = 0.99
Aspect_Ratio = 1.5
[[Fault_Model.MFD_Model]]
Model_Name = "YoungsCoppersmithCharacteristic"
MFD_spacing = 0.1
Model_Weight = 0.5
Minimum_Magnitude = 4.8
Maximum_Magnitude = 8
b_value = [ 0.868, 0.057,]

[[Fault_Model.MFD_Model]]
Model_Name = "AndersonLucoArbitrary"
Model_Type = "First"
MFD_spacing = 0.1
Model_Weight = 0.5
Minimum_Magnitude = 4.8
Maximum_Magnitude = 8
b_value = [ 0.868, 0.057,]


[Fault_Model.Fault_Geometry]
Fault_Typology = "Simple"
Fault_Trace = [ 119.153572081965, 16.4295006746644, 119.161115880619, 16.1840803955984, 119.048237064563, 15.8212857692178, 119.143208279443, 15.5128191474036, 119.012894916887, 15.2132701218065, 119.054573575693, 14.6418506764076, 119.113289191592, 14.0644876276553,]
Upper_Depth = 0
Lower_Depth = 50
Dip = 45
[Fault_Model.Slip]
Value = [ 4.0, 20.0, 25.0, 100.0, 116.0,]
Weight = [ 0.2, 0.25, 0.35, 0.1, 0.1,]
[Fault_Model.Shear_Modulus]
Value = [ 30.0,]
Weight = [ 1.0,]
[Fault_Model.Magnitude_Scaling_Relation]
Value = [ "StrasserInterface",]
Weight = [ 1.0,]
[Fault_Model.Scaling_Relation_Sigma]
Value = [ 0.0,]
Weight = [ 1.0,]
[Fault_Model.Displacement_Length_Ratio]
Value = [ 1.25e-5,]
Weight = [ 1.0,]
